TagMyPlant/Controllers/DeviceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TagMyPlant;
using TagMyPlant.Data;
using TagMyPlant.Models;
using System.IO;

namespace TagMyPlant.Controllers
{
    public class DeviceController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _hostingEnvironment;
        public DeviceController(ApplicationDbContext db, IWebHostEnvironment hostingEnvironment)
        {
            _db = db;
            _hostingEnvironment = hostingEnvironment;
        }
        public IActionResult Index()
        {
            IEnumerable<Device> objDeviceList = _db.Devices;
            return View(objDeviceList);
        }
        //Get
        public IActionResult Create()
        {
            return View();
        }
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Device obj, IFormFile? imageFile, IFormFile? pdfFileDE, IFormFile? pdfFileGB)
        {
            if (ModelState.IsValid)
            {
                if (IsDeviceExists(obj.Name, obj.Code))
                {
                    ModelState.AddModelError(string.Empty, "Device with the same name or barcode has been registered.");
                    TempData["error"] = "Device with the same name or barcode has been registered";
                    return View(obj);
                }

                // Get device name
                string deviceName = obj.Name;

                //Build the path to the device folder
                string deviceFolderPath = Path.Combine(_hostingEnvironment.WebRootPath, "KVA-datasheets", deviceName);

                // Check if the device folder exists, if not create it
                if (!Directory.Exists(deviceFolderPath))
                {
                    Directory.CreateDirectory(deviceFolderPath);
                }

                //Save image file
                if (imageFile != null && imageFile.Length > 0)
                {
                    string imageFileName = Path.GetFileName(imageFile.FileName); // Get the original file name of the uploaded file
                    string imageFilePath = Path.Combine(deviceFolderPath, imageFileName); // Use the uploaded image name as the save file name
                    using (var stream = new FileStream(imageFilePath, FileMode.Create))
                    {
                        imageFile.CopyTo(stream);
                    }
                    // Update the ImageURL field in the database to the URL of the image
                    obj.ImageURL = "/KVA-datasheets/" + deviceName + "/" + imageFileName; // Set to relative URL
                }

                // Save PDF file - DE
                if (pdfFileDE != null && pdfFileDE.Length > 0)
                {
                    string pdfFileNameDE = Path.GetFileName(pdfFileDE.FileName); // Get the original file name of the uploaded file
                    string pdfFilePathDE = Path.Combine(deviceFolderPath, pdfFileNameDE); // Use the uploaded file name as the save file name
                    using (var stream = new FileStream(pdfFilePathDE, FileMode.Create))
                    {
                        pdfFileDE.CopyTo(stream);
                    }
                    // Update the PdfUrlDE field in the database to the URL of the PDF file
                    obj.PdfUrlDE = "/KVA-datasheets/" + deviceName + "/" + pdfFileNameDE; // Set to relative URL
                }

                // Save PDF file - GB
                if (pdfFileGB != null && pdfFileGB.Length > 0)
                {
                    string pdfFileNameGB = Path.GetFileName(pdfFileGB.FileName); // Get the original file name of the uploaded file
                    string pdfFilePathGB = Path.Combine(deviceFolderPath, pdfFileNameGB); // Use the uploaded file name as the save file name
                    using (var stream = new FileStream(pdfFilePathGB, FileMode.Create))
                    {
                        pdfFileGB.CopyTo(stream);
                    }
                    // Update the PdfUrlGB field in the database to the URL of the PDF file
                    obj.PdfUrlGB = "/KVA-datasheets/" + deviceName + "/" + pdfFileNameGB; // Set to relative URL
                }

                _db.Devices.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Device created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //Get
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var deviceFromDb = _db.Devices
        .FirstOrDefault(d => d.Id == id);
            if (deviceFromDb == null)
            {
                return NotFound();
            }
            return View(deviceFromDb);
        }
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Device obj, IFormFile? imageFile, IFormFile? pdfFileDE, IFormFile? pdfFileGB)
        {
            var deviceFromDb = _db.Devices.FirstOrDefault(d => d.Id == obj.Id);
            if (ModelState.IsValid)
            {
                if (IsDeviceExists(obj.Name, obj.Code))
                {
                    ModelState.AddModelError(string.Empty, "Device with the same name or barcode has been registered.");
                    TempData["error"] = "Device with the same name or barcode has been registet";
                    return View(obj);
                }
                if (imageFile != null && imageFile.Length > 0)
                {
                    // Delete old image files
                    if (!string.IsNullOrEmpty(deviceFromDb.ImageURL))
                    {
                        string oldImagePath = Path.Combine(_hostingEnvironment.WebRootPath, deviceFromDb.ImageURL.TrimStart('/'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }
                    // Save new image file
                    string newImageFileName = Path.GetFileName(imageFile.FileName);
                    string newImageFilePath = Path.Combine(_hostingEnvironment.WebRootPath, "KVA-datasheets", obj.Name, newImageFileName);
                    using (var stream = new FileStream(newImageFilePath, FileMode.Create))
                    {
                        imageFile.CopyTo(stream);
                    }
                    obj.ImageURL = "/KVA-datasheets/" + obj.Name + "/" + newImageFileName; // Update image URL
                }
                
                if (pdfFileDE != null && pdfFileDE.Length > 0)
                {
                    // Delete old PDF files - DE
                    if (!string.IsNullOrEmpty(deviceFromDb.PdfUrlDE))
                    {
                        string oldPdfPathDE = Path.Combine(_hostingEnvironment.WebRootPath, deviceFromDb.PdfUrlDE.TrimStart('/'));
                        if (System.IO.File.Exists(oldPdfPathDE))
                        {
                            System.IO.File.Delete(oldPdfPathDE);
                        }
                    }
                    // Save new PDF file - DE
                    string newPdfFileNameDE = Path.GetFileName(pdfFileDE.FileName);
                    string newPdfFilePathDE = Path.Combine(_hostingEnvironment.WebRootPath, "KVA-datasheets", obj.Name, newPdfFileNameDE);
                    using (var stream = new FileStream(newPdfFilePathDE, FileMode.Create))
                    {
                        pdfFileDE.CopyTo(stream);
                    }
                    obj.PdfUrlDE = "/KVA-datasheets/" + obj.Name + "/" + newPdfFileNameDE; // Update PDF URL (DE)
                }
               
                if (pdfFileGB != null && pdfFileGB.Length > 0)
                {
                    // Delete old PDF files - GB
                    if (!string.IsNullOrEmpty(deviceFromDb.PdfUrlGB))
                    {
                        string oldPdfPathGB = Path.Combine(_hostingEnvironment.WebRootPath, deviceFromDb.PdfUrlGB.TrimStart('/'));
                        if (System.IO.File.Exists(oldPdfPathGB))
                        {
                            System.IO.File.Delete(oldPdfPathGB);
                        }
                    }
                    // Save new PDF file - GB
                    string newPdfFileNameGB = Path.GetFileName(pdfFileGB.FileName);
                    string newPdfFilePathGB = Path.Combine(_hostingEnvironment.WebRootPath, "KVA-datasheets", obj.Name, newPdfFileNameGB);
                    using (var stream = new FileStream(newPdfFilePathGB, FileMode.Create))
                    {
                        pdfFileGB.CopyTo(stream);
                    }
                    obj.PdfUrlGB = "/KVA-datasheets/" + obj.Name + "/" + newPdfFileNameGB; // Update PDF URL (GB)
                }

                //Update device information in the database
                _db.Devices.Update(obj);
                _db.SaveChanges();

                TempData["success"] = "Device updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //Get
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var deviceFromDb = _db.Devices
        .FirstOrDefault(d => d.Id == id);
            if (deviceFromDb == null)
            {
                return NotFound();
            }
            return View(deviceFromDb);
        }
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _db.Devices.Find(id);
            if (obj == null)
            {

TagMyPlant/Controllers/ScannerController.cs
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.ObjectModel;
using TagMyPlant;
using TagMyPlant.Data;

namespace TagMyPlantWeb.Controllers
{
    public class ScannerController : Controller
    {
        
        private readonly ApplicationDbContext _db;
        public ScannerController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Scan()
        {            
            return View();
        }
        
        public IActionResult ScanResult(string scandata)
        {
            if (scandata != null && System.Text.RegularExpressions.Regex.IsMatch(scandata, @"^\d+$"))
            {
                var deviceFromDb = _db.Devices
                    .FirstOrDefault(d => d.Code == scandata);

                if (deviceFromDb == null)
                {
                    return BadRequest("Device with barcode"+ " " + scandata + " " + "is not found!");
                }

                return View(deviceFromDb);
            }
            else
            {
                return BadRequest("Invalid input. Please enter a valid integer.");
            }
        }
    }
}

TagMyPlant/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TagMyPlant</title>
    <link rel="stylesheet" href="~/css/bootswatchThema.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/TagMyPlant.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />
    <style>
        .table-divider tr td,
        .table-divider tr th {
            border: 1px solid #000; 
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">TagMyPlant</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Device" asp-action="Index">Device</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Scanner" asp-action="Scan">Scan</a>
                        </li>
                        @*
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>*@
                    </ul>
                    @*<form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>*@
                </div>
            </div>
        </nav>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TagMyPlant - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TagMyPlant/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~\lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}